version: 2
registries:
  rubygems-server-gems-contribsys-com:
    type: rubygems-server
    url: https://gems.contribsys.com
    username: "${{secrets.RUBYGEMS_SERVER_GEMS_CONTRIBSYS_COM_USERNAME}}"
    password: "${{secrets.RUBYGEMS_SERVER_GEMS_CONTRIBSYS_COM_PASSWORD}}"

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    timezone: America/New_York
  open-pull-requests-limit: 10
  assignees:
  - gibbonas
  - ryanvall
  - nicreed
  - DougKeller
  labels:
  - dependencies
  ignore:
  - dependency-name: regexp_parser
    versions:
    - 2.0.3
  - dependency-name: docile
    versions:
    - 1.3.4
  - dependency-name: rspec-support
    versions:
    - 3.10.1
  - dependency-name: rspec-mocks
    versions:
    - 3.10.1
  registries:
  - rubygems-server-gems-contribsys-com
