Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Enabled: true
  Exclude:
    - spec/**/*

Lint/UselessAssignment:
  Enabled: true
  Exclude:
    - spec/**/*

AllCops:
  Exclude:
    - ./*.gemspec

Naming/VariableNumber:
  Enabled: false

Naming/FileName:
  Enabled: false
