version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "monthly"
    default_assignees:
      - "gibbonas"
      - "ryanvall"
      - "nicreed"
      - "DougKeller"
    default_labels:
      - "dependencies"
    allowed_updates:
      - match:
          update_type: "all"
